### ISSUE TITLE
Support for this module?

### ISSUE THREAD

**Issue by iainelder** [avlcloudtechnologies/terraform-aws-sso#4]
Hi, @aurimasmick ,

Today I browsed the Terraform Registry for modules to set up AWS SSO.

Of all the options, I like this one the most because of its detailed complete example. It seems to match my use case really well. I especially like the use of AWS Organizations as a data source to add common roles to all the accounts automatically.

What is the best way to get support if I have questions about using this module to configure my AWS SSO instance?

**Comment by aurimasmick** [comment]
Hi @iainelder,

Glad you found the module useful.  Feel free to post any questions you have in here on github issues and I'll do my best to answer them as soon as possible. Many thanks.

**Comment by iainelder** [comment]
Thanks! That works for me.
