### ISSUE TITLE
Support for AWS SSO IAM customer managed policies

### ISSUE THREAD

**Issue by bruman** [avlcloudtechnologies/terraform-aws-sso#7]
Amazon just released a new feature. 

https://aws.amazon.com/about-aws/whats-new/2022/07/aws-single-sign-on-aws-sso-aws-identity-access-management-iam-customer-managed-policies-cmps/

It would be awesome if this was added to the terrafrom-aws-sso module. On looking at the release is sounds like we can now add IAM customer managed policies to the SSO permission sets, so we can do stuff like use the same IAM policy on an IAM user or OIDC role as an SSO user.

**Comment by smaruy30** [comment]
terraform has the [resource type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_customer_managed_policy_attachment).
I can make PR, I think.
