### ISSUE TITLE
Breaking Change in AWS 4.34.0 (October 6, 2022)

### ISSUE THREAD

**Issue by bruman** [avlcloudtechnologies/terraform-aws-sso#9]
Breaking Change in AWS 4.34.0 (October 6, 2022)
https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md

Getting warning:
Getting errors when using principal_name = user@corpdomain.com
Warning Argument us deprecated
with data.aws_identificationstore_user.this['user@corpdomain.com']
Use the alternative_identifier attribute instead

And and error. 
Error: reading AWS SSO Identity Store User Data Source (d-1234): operation error identitystore: GetUserId, https response error StatusCode: 400, RequestID: 378ec509-e62e-4f8b-80a5-e6ecf7c93f28, api error UnknownOperationException: UnknownError
│
│   with module.aws-sso.module.sso.data.aws_identitystore_user.this["[user@corp.com](mailto:jmartin@corp.successkpi.com)"],
│   on .terraform/modules/aws-sso.sso/main.tf line 48, in data "aws_identitystore_user" "this":
│   48: data "aws_identitystore_user" "this" {
│

**Comment by aurimasmick** [comment]
Apologies for the delay. Unfortunately I wasn't able to reproduce the issue that you were having. I changed the filtering syntax and bumped the required provider. Let me know if it's still an issue.
